[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Upload speed and monitor speed
upload_speed = 921600
monitor_speed = 115200

; Dependencies
lib_deps =
    lvgl/lvgl @ ^8.3.0
    bodmer/TFT_eSPI @ ^2.5.43
    XPT2046_Touchscreen

; Include path so LVGL (in libdeps) finds our lv_conf.h
build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
    -std=gnu++17